name: Metrics

on:
  page_build:
  schedule:
    - cron: '55 0 * * *'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_pagespeed: yes
          plugin_pagespeed_url: mytestdummy.github.io
